# Generated by Django 4.2 on 2024-09-27 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_customuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otpverification',
            name='user',
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
        migrations.DeleteModel(
            name='OTPVerification',
        ),
    ]
